# Generated by Django 4.0.3 on 2022-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('pic', models.FileField(default='avatar.png', upload_to='profile')),
            ],
        ),
    ]
