# Generated by Django 4.0.3 on 2022-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
