# Generated by Django 4.0.3 on 2022-04-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointments'),
        ('Lab', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Lappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=25)),
                ('pay_id', models.CharField(max_length=20)),
                ('verify', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('pay_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.assistants')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.test')),
            ],
        ),
    ]
