# Generated by Django 4.0.3 on 2022-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_alter_test_amount_lappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lappointment',
            name='pay_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
