# Generated by Django 4.0.3 on 2022-04-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('doctoremail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('specialization', models.CharField(max_length=30)),
                ('doc_pic', models.FileField(default='doc.png', upload_to='profile')),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
